const base = import.meta.env.BASE_URL;

const membersData = [
  {
    name: "Diya Pandley",
    role: "President",
    major: "Computer Science with Applied Mathematics Minor",
    year: "2027",
    image: `${base}img/diya.jpeg`,
    funFact: "Loves literature, gardening and traveling! ",
  },
  {
    name: "Sophia Chen",
    role: "Vice President",
    major: "Computer Science & Business",
    year: "2027",
    image: `${base}img/sophia.png`,
    funFact: "I love travelling to other countries, especially trying the local foods.",
  },
  {
    name: "Nina Chau",
    role: "Web Development Lead",
    major: "Computer Science + UX Design in IDEAS Program",
    year: "2027",
    image: `${base}img/nina.jpg`,
    funFact: "I enjoy game development!",
  },
  {
    name: "Laura Sommer",
    role: "Treasurer",
    major: "Computer Science",
    year: "2028",
    image: `${base}img/laura.jpg`,
    funFact: "Has planned events for 500+ people 🎉",
  },
  {
    name: "Sadie Thomas",
    role: "Internal Events",
    major: "Computer Science & Business",
    year: "2027",
    image: `${base}img/sadie.png`,
    funFact: "I love going to cat cafes!",
  },
  {
    name: "Maisy Earl",
    role: "Marketing",
    major: "Computer Science",
    year: "2027",
    image: `${base}img/maisy.png`,
    funFact: "I'm from Scranton PA, where The Office takes place!",
  },
  {
    name: "Vini Jaiswal",
    role: "External Relations",
    major: "Computer Science",
    year: "2027",
    image: `${base}img/vini.jpg`,
    funFact: "If I were a fish, I'd love to be a jellyfish",
  },
  {
    name: "Alice Peng",
    role: "External Events",
    major: "Computer Science",
    year: "2028",
    image: `${base}img/alice.jpg`,
    funFact: "xxx",
  },
  {
    name: "Nia Matthew",
    role: "Freshman Representative Duckling",
    major: "Business Information Systems and Finance",
    year: "2029",
    image: `${base}img/nia.png`,
    funFact: "I'm the only person in my family who is left handed",
  },
  {
    name: "Sydney Sedlock",
    role: "Marketing Duckling",
    major: "Finance",
    year: "2029",
    image: `${base}img/sydney.JPG`,
    funFact: "I can juggle!",
  },
  {
    name: "Kripa Krishnamurthy",
    role: "Events Duckling",
    major: "Computer Science and Engineering",
    year: "2028",
    image: `${base}img/kripa.png`,
    funFact: "I have moved to a different place across the country every year from kindergarten to middle school!",
  },
  {
    name: "Nithya Sree Nagarajan",
    role: "Events Duckling",
    major: "Computer Science",
    year: "2029",
    image: `${base}img/nithya.png`,
    funFact: "I work as Lehigh CSB Website Developer ",
  },
  {
    name: "Nadxieli Jimenez Bielma",
    role: "Web Dev Team",
    major: "Computer Science & Graphic Design in IDEAS Program",
    year: "2027",
    image: `${base}img/nadxieli.JPG`,
    funFact: "I've backpacked through the Absaroka Range! ",
  },
  {
    name: "Alicia Tyagi",
    role: "Web Dev Team",
    major: "Computer Science",
    year: "2028",
    image: `${base}img/alicia.png`,
    funFact: "I have a dog named Rio ",
  },
  {
    name: "Guranaad Kaur",
    role: "Web Dev Team",
    major: "Computer Engineering",
    year: "2028",
    image: `${base}img/guranaad.png`,
    funFact: "I have a twin!",
  },
];